go_arch: amd64

# cpu is related to freq/throttling and others
# vmstat is not enabled as meminfo is enough
# ntp is useful enough to monitor local ntp daemon, but 1ms is too low for NTP Pool
# systemd provides TOO many useless metrics, although unit-whitelist may be used
# TODO: check if diskstats / netdev should ignore some devices
node_exporter_collectors: >
  --no-collector.arp --no-collector.bcache --no-collector.infiniband
  --no-collector.ipvs --no-collector.wifi --no-collector.zfs
  --collector.ntp --collector.ntp.local-offset-tolerance=5ms
  {% if ansible_service_mgr == 'systemd' %}
  --collector.systemd --collector.systemd.unit-whitelist=^$
  {% endif %}

node_exporter_disk_ignored: ""

node_exporter_base: /srv/node_exporter
node_exporter_textfiles_path: /run/nodeexp
node_exporter_version: 0.15.2
node_exporter_download_url: https://github.com/prometheus/node_exporter/releases/download

node_exporter_basename: "node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}"
node_exporter_tarball_url: "{{ node_exporter_download_url }}/v{{ node_exporter_version }}/{{ node_exporter_basename}}.tar.gz"
node_exporter_sha256sums_url: "{{ node_exporter_download_url }}/v{{ node_exporter_version }}/sha256sums.txt"
node_exporter_sha256sums: "{{ playbook_dir }}/cache/node_exporter-{{ node_exporter_version}}.SHA256SUMS"
node_exporter_path: "{{ node_exporter_base }}/{{ node_exporter_basename }}"

node_exporter_ipv4: '{{ CHANGE_ME }}'
node_exporter_listen_address: "{{ node_exporter_ipv4 }}:9100"
