---
- name: setup anycast
  include_tasks: setup-anycast.yml
  when:
  - "anycast_ip is defined"
  - "anycast_gateway is defined"
  - "blackhole_ip is defined"
  - "blackhole_gateway is defined"

- name: probe-services nginx config
  template: src=probe-services-nginx dest=/etc/nginx/sites-enabled/probe-services
  notify: reload nginx

- name: mkdir for config and data
  file:
    path: "{{ item }}"
    state: directory
    mode: "u=rwx,g=rx,o="
  with_items:
    - "{{ orchestrate_data_dir }}"
    - "{{ registry_data_dir }}"

- name: Configure orchestrate
  template:
    src: ooni-orchestrate.toml
    dest: "{{ orchestrate_data_dir }}/ooni-orchestrate.toml"

- name: Write Psiphon config file
  copy:
    content: "{{ orchestra_psiphon_config_file_content }}"
    dest: "{{ orchestra_psiphon_config_file }}"

- name: Write tor targets file
  template:
    src: tor_targets.json
    dest: "{{ orchestra_tor_targets_file }}"

- name: orchestrate webservice
  docker_container:
    image: "{{ orchestrate_docker_image }}"
    name: orchestrate
    hostname: orchestrate
    ports:
    - "{{ orchestrate_port }}:{{ orchestrate_port }}"
    volumes:
    - "{{ orchestrate_data_dir }}:{{ orchestrate_data_dir }}"
    command: "ooni-orchestrate --config {{ orchestrate_data_dir }}/ooni-orchestrate.toml start"
    restart_policy: unless-stopped

- name: Configure registry
  template:
    src: ooni-registry.toml
    dest: "{{ registry_data_dir }}/ooni-registry.toml"

- name: registry webservice
  docker_container:
    image: "{{ registry_docker_image }}"
    name: registry
    hostname: registry
    ports:
    - "{{ registry_port }}:{{ registry_port }}"
    volumes:
    - "{{ registry_data_dir }}:{{ registry_data_dir }}"
    command: "ooni-registry --config {{ registry_data_dir }}/ooni-registry.toml start"
    restart_policy: unless-stopped
