---
# I have no idea how it is implemented, but it reduces playbook runtime by factor of three!
ansible_ssh_pipelining: true

# default: login as user & get sudo
ansible_become: true

apt_cache_valid_time: 28800 # 8h

# link vault to plaintext
weasel_login: "{{ vault_weasel_login }}"
weasel_comment: "{{ vault_weasel_comment }}"
weasel_keys: "{{ vault_weasel_keys }}"
root_password_digest: '{{ vault_root_password_digest }}'
root_password_mtime: '{{ vault_root_password_mtime }}'

passwd:
  # services
  # - uid [2000, 10000), grouped together by "service"
  # - base for next service is `echo $(( 2000 + 50*($RANDOM % 160) ))`
  # - login name must be <= 8 chars to be nice to `top` util
  afredis:  {login: afredis,  id: 2000, comment: Airflow Redis}
  afpsql:   {login: afpsql,   id: 2001, comment: Airflow Postgresql}
  afsched:  {login: afsched,  id: 2002, comment: Airflow Scheduler}
  afwebsrv: {login: afwebsrv, id: 2003, comment: Airflow Webserver}
  afworker: {login: afworker, id: 2004, comment: Airflow Worker}
  afflower: {login: afflower, id: 2005, comment: Airflow Celery Flower}

  plpsql:   {login: plpsql,   id: 2100, comment: Pipeline Postgresql}
  plshovel: {login: plshovel, id: 2101, comment: Pipeline Shovel}

  nodeexp:  {login: nodeexp,  id: 2200, comment: Prometheus Node Exporter}
  prometh:  {login: prometh,  id: 2201, comment: Prometheus Poller}
  alertman: {login: alertman, id: 2202, comment: Prometheus Alert Manager}
  prombbox: {login: prombbox, id: 2203, comment: Prometheus Blackbox Exporter}
  grafana:  {login: grafana,  id: 2204, comment: Grafana for Prometheus}
  ngxprom:  {login: ngxprom,  id: 2205, comment: nginx for Prometheus exporters}
  pushgw:   {login: pushgw,   id: 2206, comment: Prometheus Pushgateway}

  piwik:    {login: piwik,    id: 2300, comment: Piwik user}

  grav:     {login: grav,     id: 2400, comment: Grav user}

  prtreg:   {login: prtreg,   id: 4800, comment: Orchestration Registry}
  prtevent: {login: prtevent, id: 4801, comment: Orchestration Events}
  prtnotif: {login: prtnotif, id: 4802, comment: Orchestration Notifications}
  prtfront: {login: prtfront, id: 4803, comment: Orchestration Front}

  explorer: {login: explorer, id: 4950, comment: OONI Explorer}

  oomsmweb: {login: oomsmweb, id: 5050, comment: OONI Measurements WebAPI}

  anaconda: {login: anaconda, id: 6000, comment: Anaconda python user}
  jupyter: {login: jupyter, id: 6001, comment: Jupyter python user}

  ooni_run: {login: oonirun, id: 7000, comment: OONI Run user}

  # people have id >= 10000
  agrabeli:
    login: agrabeli
    id: 10000
    comment: Maria Xynou
    keys: ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDD0JSwM+t3Uz9lS3Mjoz9oo4vOToWyzboZhYQbP8JY5HvFtAvWanWHnUBO91t6hkgKIMiUqhdCJn26fqkhSGe/bRBaFUocOmuyfcmZoRdi0qzAskmycJsj/w6vWR4x6MYkmJvSeI/MGxjEFt4s2MfOG1tP8CBLUYft9qUleeJa7Jln8c+xbnqB7YngaI190icQHE9NuIB2CXvzbmo3tLtHNMagEwI7VoBDj6mxzTxBd9JhuhF4w5uGxxm0Gp1hzk+15obNnaBS+Anr7jXz8FPwwxCH+XhBZxB1PPpcIayKrf9iLyGtwmhkdDoWCqYAr1mue3LxFso+TZF4bwE4Cjt1 agrabelh@agrabelh"]
  weasel:
    login: "{{ weasel_login }}"
    id: 10001
    comment: "{{ weasel_comment }}"
    keys: "{{ weasel_keys }}"
  art:
    login: art
    id: 10002
    comment: Arturo Filasto
    keys: ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9her6lZIfP/ulXleu00u3ukdcVEDslkfXzi65JFRXRkKYsdMw7zLvrkvFryqDGsRQwpZo0rlk5o26QNSUR/g2Kf3wEHxxmMcN4+g+f0/fJDKLHSFdL5Z5ACyp5YvjA88vG753qVn7lBINuvCb4wk1sUOWM1WVG5WiszLiJCddYUrgCZWzD3FHyApJ/GGH2A5vTTN8mcQapQaJ9/sgxDw5WT+yMtZ8TW4462x+TaWWGE0WnAd/l6HOFaS14mql0K+MbtRp9EKN2O6+sA0OsjknYpt21ovtEWfBiojjh+4Iz6bTk+M5+fWHwQaxqEcaok22l35GudlmaoTB0OesB/1z art@eclipsis"]
  darkk:
    login: darkk
    id: 10003
    comment: Leonid Evdokimov
    keys: ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWe9jGACZhSKhCq/jGOe8xKpY8bPSC8MagEiWMCzcHA5520Js4EGzwuYx5h/7sHK4GKWekGzO57xOsgeKACDKo8JppIPt+uJtnwJpVr7EHdnX1hhBMfo0NfV42R+//fZIHMNtGIW31iPg3cQVp9c+GQPsdmuDPbKGLoQvS9dGnF+N6lM+dicEmeBrqbA/t5V1j/rrfpmpTNOWef2WsREFdZBQbgD3rZU1lG0CnxNw6ATnFQgqcC1QsyfWD8e1pmDLByoVuYJ6WXBLKgI86hrMNidxGjzmpAn2q+5cbu5HZXOkmny3TBiP0VxPJJ43PuLIFkdCNh50KRPtTug3o38Oj leon+2016@darkk.net.ru"]
  nuke:
    login: nuke
    id: 10004
    comment: Lorenzo Primiterra
    keys: ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+QtDwA/s8vw7aETWGjItUBmgCXgm9jTEjCh/5OofGJ/Bk4kjZ+a6NisUNJRvrySfr89oeJz7VOuHgHTCM1g2CKANAiidcBkepHjdBlHDElV1WBlUxdgl0RsbM4ue8zUxtrmzEQaxLxL769ZHR+gI8PoZau1cSyKG5jVge91Bt1+wvV3dMGvxibM144+uHCrxHpBsbRd9irIgk+vNJmecKn3bSh3aKo9txBjIqBprBrZ1Dqj0x9IKVhD59URcO1Vrr3HXPghZnsWFjOSSQ0DeVpkE3cEz78CpdvqL0drv4Mo1ZgE33YLwWjJSceDGIrtnsPZhs5YzOI4iStRIdPD4X nuke"]
  sbs:
    login: sbs
    id: 10005
    comment: Simone Basso
    keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQChiA7/HyB2fcXulsT33NF7N+681A4u3JRjl/d85JCjYycnw+gYl2Q/aovZ31Y64VC3AYwXwHp6lx2GwfTe0R+4Wk0qriFYnDhnjG6uiFEdatJWb1/yyGkJ31XOMoOBEPRrqhjmpHDmLvyhD1J0UIfk+5jsV3SIOXUMTKO9NDbUT0fu4d85/IFGteip6tVu3eKHNVLHQJhxkvOwN9B4WLNbALW4TlFqYfUX0Stz4ijguVNKdeIjNq74DbyTYRWm/DEMFpwIrBDuupg8I2InXbYFRU8H7avIvBc7UWhFVm5yvLkTnq5DltERt6dDAEdT6PdGyrP9Zf0vgGgfvc6c8gFTKdm7xoGCUgYYMak/m6AOaiB/18HRGVF97XEwN1VUB0pOkGNOLwgS/DbrDvonrnDC4Du6nuGJ56Wz2mH1kxG0AWY++NamtCrm7gUrmbmeHhjIVwfea1AKaQUEwgxeV5woiW4NGX3Im/GWr1pwqvbIZ2ple9AGzA2+JBfHDetKJZOVhF0hdUzGXa1y+vLykRiZ+dCy5WFw2prBmREv9BvUutGIn9qwR9NbFHsft/P4n5BS8AzNox9nSog6YPm0Qbsg5LIDxfD0Z6uw9l9KsinrJ4fn/08rJrSIAvh2pORuXPWIXU3321Pt2o0nwmWncL/spVh2Fjrkt3Iuh5668c2wjw== simone@shelob"
      - "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOODb6hoif8TDyU2KZ73mfc0zjy4dy/1a6wZwpd3hmdLGmMHPEMtl8KjeLCo8uGVPK4dDE4NGBcWeYCPJofuQWk= sbasso@dunkerque.local"
  superq:
    login: superq
    id: 10006
    comment: Ben Kochie
    keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDfYfZFTGkdHoRoUfnhzp8RLuOgOEgyTH4dncpP+eN2yBbTw5kY84t8sSa60vtjfiPFQGBYaBZdZV9hTdOZgR+wyQXeSWy2evM9e/6h9ZCwhV8vXiRsisV7cJyuqfTdeTaqwgggR24ETS6nTs8UEPRjfzXDTPGv8e4B4vcvoGjEtgkWfOD1V10RuULxZc+kccxYWopTsnpEdrO1o/3IDlno8+7cTNFYDV+HEdjr7BMWXJJvuqW+59WQzkwggQtLLL72gQD2VrDb9+1g0xWSRBd1Jp/Yv956uLJGaVGjJ2yOdyy5nNAqoTRYPoRniMnGOOHPk6fR1LsqXK5S4hxyInTEQvszKUwz0aRDITxtHxdBlruYaAotGB2VEMax3h4t2HJRYsEt+zxgh+ZEDJTsk0GgywO01obn9dgrCF2gwa4DUR2trcc4uaW0ZbqzQ9PiOZ6+ENYJiR6DkXWSrVXB75Vo9tw0DAC/ArxHJ6kl9W52h0Z7hFDQrniRAmYCWF7/jOhFYuqvzmeLOZJajJ9TE4Z5an0maeYchsISODeVaQWQ8ZPSR/9WjXFtVRMu57H+MVsvgNodaq/G2y7Y+S0djjKAUVtqPiM/AUDXCk88eHl0XfSgUEoveuMZiWfgcGW28LoF36OMihTwx6xJ5bLxVUp+FkLIM+3ET/foabLupCIAoQ== superq"

adm_logins: [ weasel, art, darkk, sbs ]

# to avoid useless `pip` modules in global environment if ansible modules require it
ansible_venv: /root/venv
docker_apt_ver: ""

# that's common for roles nginx-prometheus, fw and various exporters
node_exporter_ipv4: "127.139.92.143" # this addr is not 127.0.0.1 to avoid confusion as external/9100 is SSL and lo/9100 is not
ngxprom_exporter_ports: { 9100: '{{ node_exporter_ipv4 }}' }

ntp_pool: debian
have_ssd: false
...
