---
- name: Create vg.metadb Volume Group
  lvg:
    vg: vg.metadb
    pvs:
      - /dev/xvdb1
      - /dev/xvdc1
      - /dev/xvdd1
      - /dev/xvde1
      - /dev/xvdf1
      - /dev/xvdg1
      - /dev/xvdh1

- name: Create metadb logical volume
  lvol:
    vg: vg.metadb
    lv: metadb
    size: 100%VG

- name: Create filesystem for metadb
  filesystem:
    fstype: ext4
    dev: /dev/vg.metadb/metadb
    opts: -L metadb

- name: Mount metadb FS
  mount:
    fstype: ext4
    opts: noatime
    path: /var/lib/postgres
    src: LABEL=metadb
    state: mounted

- name: install PG11 and its prom exporter
  apt:
    cache_valid_time: 86400
    name:
      - postgresql-11
      - prometheus-postgres-exporter

- name: Trust localhost IPv4 access on postgresql
  lineinfile:
    dest: /etc/postgresql/11/main/pg_hba.conf
    regexp: '^host\s+all\s+all+\s+127\.0\.0\.1/32\s+trust'
    insertafter: '^# IPv4 local connections:'
    line: "host    all             all             127.0.0.1/32            trust"
    state: present

- name: Reload pg after conf change
  service: name=postgresql state=reloaded

- name: allow prometheus-postgres-exporter.service
  blockinfile:
    path: /etc/ooni/nftables/tcp/9187.nft
    create: yes
    block: |
      add rule inet filter input tcp dport 9187 counter accept comment "prometheus-postgres-exporter.service"

- name: reload nftables service
  systemd:
    name: nftables.service
    state: reloaded

