- name: Check if proteus-frontend.service exists
  stat: path=/etc/systemd/system/proteus-frontend.service
  register: proteus_frontend

- name: Stop proteus-frontend.service
  systemd:
    name: proteus-frontend.service
    state: stopped
    enabled: no
    daemon_reload: yes
  when: proteus_frontend.stat.exists == True

- name: Cleanup proteus legacy files
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "/etc/systemd/system/proteus-frontend.service"
    - "/etc/nginx/sites-enabled/proteus"
