---
groups:
- name: Basic prometheus
  rules:
  - alert: SPbNoonCannon
    expr: (hour() == 8) and (minute() >= 55)
    labels: {severity: keepalive_spb}
    annotations:
      summary: 'Noon cannon in St.Petersburg fires soon'

  # node_timex_sync_status is not enabled right now as old NTP daemons do not update `timex`
  - alert: NTPOutOfSync
    expr: (node_scrape_collector_success{collector="ntp"} != 1) or (node_ntp_sanity != 1) # or (node_timex_sync_status != 1)
    for: 1h
    labels: {severity: info}

  # including http scraping failure
  - alert: InstanceDown
    expr: up != 1
    for: 5m
    annotations:
      summary: '{{ $labels.instance }} is not `up`'

  - alert: IOWaitHigh
    expr: max(irate(node_cpu{mode="iowait"}[1m])) by (instance) > 0.9
    for: 5m # matters to avoid spikes
    annotations:
      summary: '{{ $labels.instance }} %iowait over 90%'

  # NB: node_filesystem_avail is for non-root users, node_filesystem_free is for root. They are equal for XFS.
  - alert: DiskWillFillInAWeek
    expr: 8 * node_filesystem_avail - 7 * (node_filesystem_avail offset 1d) < 0 # x75 speedup of (node_filesystem_avail + delta(node_filesystem_avail[24h])*7) < 0
    for: 1h
    annotations:
      summary: 'In a week {{ $labels.instance }} becomes /dev/full'
      description: 'In a week {{ $labels.mountpoint }} `df` will be ~ {{ $value | humanize1024 }}B.'

  # <10Gb and <20% available. Make some sense for huge storages and small ramdrives.
  - alert: DiskFull
    expr: (node_filesystem_avail < 10737418240) and (node_filesystem_avail / node_filesystem_size * 100 < 20)
    annotations:
      summary: '{{ $labels.instance }}{{ $labels.mountpoint }} is almost full'
      description: >
        {{ $value | humanize1024 }}B
        ~ {{ (printf "round(node_filesystem_avail{instance='%s',mountpoint='%s'} / node_filesystem_size * 100)" $labels.instance $labels.mountpoint) | query | first | value }}%
        available at {{ $labels.instance }}{{ $labels.mountpoint }}.

  - alert: DiskInodesOver50pct
    expr: node_filesystem_files_free / node_filesystem_files * 100 < 50
    annotations:
      summary: '`df -i` at {{ $labels.instance }} over 50%'
      description: '{{ printf "%.1f" $value }}% inodes available at {{ $labels.mountpoint }}.'

  # sub-scraping failure
  - alert: TextfileError
    expr: node_textfile_scrape_error > 0
    annotations:
      summary: 'Broken `textfile` at {{ $labels.instance }}'

  # all the textfile are updated at least hourly
  - alert: TextfileJam
    expr: (node_textfile_mtime - ON(instance,job) GROUP_LEFT() node_time) / -3600 > 2
    annotations:
      summary: 'Stale `textfile` at {{ $labels.instance }}'
      description: '`{{ $labels.file }}` is {{ printf "%.0f" $value }}h old.'

  # naive prometheus health monitoring
  - alert: ScrapeSamplesLoss
    expr: sum(scrape_samples_scraped) / sum(scrape_samples_scraped offset 24h) < 0.5
    annotations:
      summary: Lots of `scrape_samples_scraped` lost
      description: Now ~ {{ "sum(scrape_samples_scraped)" | query | first | value | humanize }}, 24h ago ~ {{ "sum(scrape_samples_scraped offset 24h)" | query | first | value | humanize }}.

  - alert: BlackboxDown
    expr: probe_success == 0
    for: 5m
    annotations:
      summary: "{{ $labels.instance }} endpoint down"

  - alert: SSLCertExpires
    expr: (probe_ssl_earliest_cert_expiry - time()) / 86400 < 25
    labels: {severity: info}
    annotations:
      summary: '`certbot` failed at {{ $labels.instance }}'
      description: 'SSL cert for  expires in {{ printf "%.0f" $value }} days.'
...
