---
anaconda_platform : '{{ansible_system}}-{{ansible_machine}}'
anaconda_name : 'Anaconda{{anaconda_python_version}}-{{anaconda_version}}-{{anaconda_platform}}'
anaconda_installer_sh : '{{anaconda_name}}.sh'
anaconda_installer_url : '{{anaconda_mirror}}/{{anaconda_installer_sh}}'
anaconda_checksum : '{{anaconda_checksums[anaconda_installer_sh]}}'

anaconda_install_dir: '{{anaconda_parent_dir}}/{{anaconda_name}}'
anaconda_link_dir: '{{anaconda_parent_dir}}/{{anaconda_link_subdir}}'
anaconda_conda_bin: '{{anaconda_link_dir}}/bin/conda'

ooni_sync_tar: 'ooni-sync_{{ ooni_sync_version }}_{{ go_platform }}_{{ go_arch }}.tar.gz'
ooni_sync_url: 'https://github.com/TheTorProject/ooni-sync/releases/download/v{{ ooni_sync_version }}/{{ooni_sync_tar }}'
ooni_sync_checksum: 'ooni_sync_checksums[ooni_sync_tar]'
