piwik_download_path: http://builds.piwik.org/piwik-3.6.0.zip

piwik_admin_user: piwik_admin
piwik_admin_email: "admin@openobservatory.org"

mysql_host: 127.0.0.1
mysql_admin_user: root
mysql_piwik_user: piwik
mysql_piwik_db: piwik_db

deploy_create_folders:
- ''
- /tmp
- /releases
- /shared
- /shared/config

piwik_user: "{{ passwd.piwik.login }}"
piwik_group: "{{ passwd.piwik.login }}"

app_name: piwik
app_user: "{{ piwik_user }}"
app_path: /srv/piwik
server_name: analytics.ooni.io
piwik_trusted_host: "analytics.ooni.io:8081"
piwik_webpage_name: "ooni.io"
piwik_webpage_url: "analytics.ooni.io"
