---
- name: add tor apt key
  apt_key: >
    keyserver="keys.gnupg.net"
    id="A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89"

- name: setup tor apt repo
  apt_repository: >
    repo='deb http://deb.torproject.org/torproject.org {{ ansible_distribution_release }} main'
    state=present 
    update_cache=yes

- name: setup tor apt repo
  apt_repository: >
    repo='deb http://deb.torproject.org/torproject.org {{ ansible_distribution_release }}-{{ tor-version }} main'
    state=present 
    update_cache=yes
  when: experimental_tor == "yes"

- name: install tor and tor keyring packages
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items: ["deb.torproject.org-keyring", "tor"]
