---

- name: installs apt-https-transport
  apt: >
    name={{ item }}
    state=present
  with_items:
    - apt-transport-https
    - python-virtualenv

- name: adds Docker repository key
  apt_key: >
    id=58118E89F3A912897C070ADBF76221572C52609D
    url="https://apt.dockerproject.org/gpg"

- name: adds Docker repository and update apt cache
  apt_repository: >
    repo="deb https://apt.dockerproject.org/repo {{ ansible_distribution|lower }}-{{ ansible_distribution_release }} main"
    update_cache=yes

- name: installs docker-engine package
  apt: name=docker-engine{{ docker_apt_ver }}

- name: enables and starts docker service
  service: >
    name=docker
    enabled=yes
    state=started

# 1. ansible 2.2.2 declares 1.7.0+ as a requirement, but it's really 1.8.0+
#    https://github.com/ansible/ansible-modules-core/issues/5515
#    https://github.com/ansible/ansible/issues/20776
# 2. 2.0 is probably unsupported due to renaming of `docker.Client` to `docker.APIClient`
#    https://docker-py.readthedocs.io/en/stable/change-log.html
- name: Install docker-py via pip in virtualenv
  pip: >
    name="docker-py"
    version="1.10.6"
    virtualenv="{{ ansible_venv }}"
