---
- name: mkdir for config and data
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  with_items:
    - "{{ grafana_config_path }}"
    - "{{ grafana_lib_path }}"

- name: configure grafana
  template:
    src: grafana.ini.j2
    dest: "{{ grafana_config_path }}/grafana.ini"

- name: docker network for grafana
  docker_network:
    name: grfn
    driver_options:
      com.docker.network.bridge.name: brgrfn
    ipam_options:
      subnet: 172.26.55.0/24
      gateway: 172.26.55.1

- name: grafana service
  docker_container:
    image: "grafana/grafana:{{ grafana_docker_tag }}"
    name: grafana
    hostname: grafana
    networks: [{name: grfn, ipv4_address: '{{ grafana_backend_ipv4 }}'}]
    volumes:
      - /etc/passwd:/etc/passwd:ro # for better `grafana` UID
      - /etc/group:/etc/group:ro
      - "{{ grafana_config_path }}:/etc/grafana"
      - "{{ grafana_lib_path }}:/var/lib/grafana"
    env:
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
      GF_SECURITY_SECRET_KEY: "{{ grafana_secret_key }}"
      # TBD: GF_USERS_{allow_sign_up,allow_org_create}, GF_AUTH_*
      # and others from http://docs.grafana.org/installation/configuration/
      GF_SERVER_HTTP_PORT: "{{ grafana_backend_port }}"
      GF_SERVER_ROOT_URL: "https://mon.ooni.nu/grafana/"
      GF_AUTH_BASIC_ENABLED: false
    restart_policy: unless-stopped
...
