---
adm_logins: [ art, federico, sarath, sbs, superq ]
ngxprom_scrapers:
  - prometheus.infra.ooni.io

onion_ipv6_ula: 'fd26:a7e3:2a3::'

# That's the password that other nodes do NOT store in config files,
# other nodes store SSHA() of it that is in group_vars/all
prometheus_scraper_password: '{{ vault_prometheus_scraper_password }}'

prometheus_basic_auth_password: "{{ vault_prometheus_basic_auth_password }}"
alertmanager_slack_api_url: '{{ vault_alertmanager_slack_api_url }}'
grafana_admin_password: "{{ vault_grafana_admin_password }}"
grafana_secret_key: "{{ vault_grafana_secret_key }}" # to sign cookies

prometheus_listen_address: "127.0.0.1:8090"
alertmanager_listen_address: "127.0.0.1:9093"
grafana_backend_ipv4: "172.26.55.254"
grafana_backend_port: 26738

ngxprom_exporter_ports:
  9100: '{{ node_exporter_ipv4 }}'
  8090: '127.0.0.1' # FIXME: unusual port for prometheus
  9093: '127.0.0.1'

blackbox_jobs:
  - name: "ooni web_connectivity test helpers"
    module: "ooni_web_connectivity_ok"
    targets:
      #- "https://a.web-connectivity.th.ooni.io/status"
      - "https://mia-wcth.ooni.io/status"
      - "https://hkg-wcth.ooni.io/status"
  - name: "ooni collector"
    module: "ooni_collector_ok"
    targets:
      #- "https://a.collector.ooni.io/invalidpath"
      - "https://b.collector.ooni.io/invalidpath" # hardcoded in MK as a fallback in case of bouncer failure
      - "https://c.collector.ooni.io/invalidpath"
      # Probe services
      - "https://ps.ooni.io/invalidpath"
  - name: "ooni bouncer"
    module: "ooni_bouncer_ok"
    targets:
      - "https://bouncer.ooni.io/bouncer/net-tests"
      - "https://ps.ooni.io/bouncer/net-tests"

  # IP addresses are used for test-helpers in monitoring configuration for some
  # historical reason hopefully remembered by @hellais.
  - name: "ooni tcp echo"
    module: "ooni_tcp_echo_ok"
    targets:
      - "{{ lookup('dig', 'c.echo.th.ooni.io/A') }}:80"

  - name: "ooni http return json headers"
    module: "ooni_http_return_json_headers_ok"
    targets:
      - "http://{{ lookup('dig', 'a.http.th.ooni.io/A') }}:80"

  - name: "ooni explorer homepage"
    module: "http_2xx"
    targets:
      - "https://explorer.ooni.org/"

  - name: "ooni API files"
    module: "http_2xx"
    targets:
      - "https://api.ooni.io/api/v1/files"

  - name: "ooni API measurements"
    module: "http_2xx"
    targets:
      - "https://api.ooni.io/api/v1/measurements"

  - name: "slack inviter"
    module: "http_2xx"
    targets:
      - "https://slack.ooni.org"

  - name: "ooni website"
    module: "http_2xx"
    targets:
      - "https://ooni.torproject.org"

  - name: "ooni get"
    module: "http_2xx"
    targets:
      - "https://get.ooni.torproject.org"

  - name: "orchestrate"
    module: "ooni_orchestrate"
    targets: [ "https://orchestrate.ooni.io:443/api/v1/test-list/urls?limit=10" ]

  - name: "registry"
    module: "ooni_registry"
    targets: [ "https://registry.proteus.ooni.io:443/api/v1/register" ]

  - name: "proteus"
    module: "ooni_proteus"
    targets: [ "https://proteus.ooni.io:443" ]

  - name: "tor testhelper" # see also SSLCertExpires in roles/prometheus/files/alert_rules.yml
    module: tls_snakeoil
    targets: "{{ groups['have_tor'] | map('regex_replace', '$', ':9001') | list }}"

  - name: ssh
    module: ssh_banner
    # staticiforme.torproject.org ssh port is only reachable via jumphost
    targets: "{{ groups['all'] | difference(['staticiforme.torproject.org']) | map('regex_replace', '$', ':22') | list }}"

  - name: icmp
    module: icmp
    targets: "{{ groups['all'] | list }}"
...
