- name: cache SHA256SUMS locally
  local_action: get_url url={{ alertmanager_sha256sums_url }} dest={{ alertmanager_sha256sums }}
- set_fact:
    tarball_checksum: "sha256:{{ lookup('pipe', 'awk -v FNAME=' ~ alertmanager_basename ~ '.tar.gz -f ' ~ playbook_dir ~ '/../scripts/get-sum.awk ' ~ alertmanager_sha256sums) }}"

- name: set permissions, owner and group
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ alertmanager_base }}"
    - "{{ alertmanager_base }}/dist"
    - "{{ alertmanager_config_path }}"
    - "{{ alertmanager_templates_path }}"

- name: mkdir for data
  file:
    path: "{{ alertmanager_data_path }}"
    state: directory
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: 0750

- name: fetch alertmanager tarball
  get_url:
    url: "{{ alertmanager_tarball_url }}"
    dest: "{{ alertmanager_base }}/dist/{{ alertmanager_basename }}.tar.gz"
    checksum: "{{ tarball_checksum }}"

- name: untar alertmanager tarball
  unarchive:
    src: "{{ alertmanager_base }}/dist/{{ alertmanager_basename }}.tar.gz"
    dest: "{{ alertmanager_base }}"
    owner: root
    group: root
    remote_src: true

- name: Configure Alertmanager templates
  notify:
  - reload alertmanager
  copy:
    src: "{{ item }}"
    dest: "{{ alertmanager_templates_path }}"
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - templates/*.tmpl
  tags: prometheus-conf

- name: Configure Alertmanager
  notify:
  - reload alertmanager
  template:
    src: alertmanager.yml.j2
    dest: "{{ alertmanager_config_path }}/alertmanager.yml"
    owner: root
    group: root
    mode: 0644
    validate: '{{ alertmanager_path }}/amtool check-config %s'
  tags: prometheus-conf

- name: Install alertmanager systemd service file
  notify:
  - systemctl daemon-reload
  - restart alertmanager
  template:
    src: alertmanager.service
    dest: /etc/systemd/system/alertmanager.service

- name: Enable and start alertmanager service
  systemd:
    name: alertmanager.service
    state: started
    enabled: yes
    daemon_reload: yes
