---
- name: Install etckeeper
  apt:
    name:
    - etckeeper
    state: latest
    update_cache: yes
    cache_valid_time: '{{ apt_cache_valid_time }}'
  when: ansible_distribution_release == 'buster'
