---
- name: Install nginx
  environment:
    RUNLEVEL: 1 # Done to avoid nginx auto starting
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx

- name: Remove default nginx virtual host
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent
  register: nginx

- name: Configure nginx
  template:
    src: etc-nginx/
    dest: /etc/nginx/

- name: Configure piwiks virtual host
  template:
    src: nginx-site-piwik.j2
    dest: /etc/nginx/sites-available/piwik

- name: Link nginx sites
  file:
    path: /etc/nginx/sites-enabled/piwik
    src: /etc/nginx/sites-available/piwik
    state: link
    force: yes
  notify:
  - restart nginx

