- name: cache SHA256SUMS locally
  local_action: get_url url={{ blackbox_exporter_sha256sums_url }} dest={{ blackbox_exporter_sha256sums }}
- set_fact:
    tarball_checksum: "sha256:{{ lookup('pipe', 'awk -v FNAME=' ~ blackbox_exporter_basename ~ '.tar.gz -f ' ~ playbook_dir ~ '/../scripts/get-sum.awk ' ~ blackbox_exporter_sha256sums) }}"

- name: Creating blackbox_exporter dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items:
    - "{{ blackbox_exporter_base }}"
    - "{{ blackbox_exporter_base }}/dist"

- name: fetch blackbox_exporter tarball
  get_url:
    url: "{{ blackbox_exporter_tarball_url }}"
    dest: "{{ blackbox_exporter_base }}/dist/{{ blackbox_exporter_basename }}.tar.gz"
    checksum: "{{ tarball_checksum }}"

- name: untar blackbox_exporter tarball
  unarchive:
    src: "{{ blackbox_exporter_base }}/dist/{{ blackbox_exporter_basename }}.tar.gz"
    dest: "{{ blackbox_exporter_base }}"
    owner: root
    group: root
    remote_src: true

# TODO: AmbientCapabilities needs systemd-229 we currently have systemd-215
- name: Set cap_net_raw for blackbox_exporter
  capabilities:
    path: '{{ blackbox_exporter_path }}/blackbox_exporter'
    capability: cap_net_raw+ep
    state: present

- name: Install config file
  template:
    src: blackbox.yml.j2
    dest: "{{ blackbox_exporter_base }}/blackbox.yml"
    owner: root
    group: root
    mode: 0644
  notify:
  - restart blackbox_exporter
  tags: prometheus-conf

- name: Install blackbox_exporter systemd service file
  notify:
  - systemctl daemon-reload
  - restart blackbox_exporter
  template:
    src: blackbox_exporter.service
    dest: /etc/systemd/system/blackbox_exporter.service

- name: Enable and start blackbox_exporter service
  systemd:
    name: blackbox_exporter.service
    state: started
    enabled: yes
    daemon_reload: yes
