---

- name: Install nginx package
  apt:
    name: nginx
    update_cache: yes

- name: Remove default nginx virtual host config
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent
  register: nginx

- name: Add nginx virtual host config
  template:
    src: nginx-ooni-get.conf.j2
    dest: /etc/nginx/sites-enabled/ooni-get
    owner: root
    group: root
    mode: 0644
  register: nginx

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  when: nginx.changed
