---
- name: create SSH config directory
  file: dest=/srv/etc/collector_ssh state=directory owner=root group=root mode=0755

- name: create sync-user role key
  command: ssh-keygen -t ed25519 -N '' -C sync-user@{{ inventory_hostname }} -f /srv/etc/collector_ssh/id_ed25519
  args:
    creates: /srv/etc/collector_ssh/id_ed25519

# TODO: `benchmark` is an ugly legacy username for uid=1000 at datacollector.infra.ooni.io, it should be eventually re-numbered
- name: set sync-user role key owner
  file: path={{item}} owner=benchmark group=benchmark
  with_items:
  - /srv/etc/collector_ssh/id_ed25519
  - /srv/etc/collector_ssh/id_ed25519.pub

- name: create known_collectors
  template: dest=/srv/etc/collector_ssh/known_collectors src=known_collectors owner=root group=root mode=0444

- name: fetch public sync-user key
  fetch: src=/srv/etc/collector_ssh/id_ed25519.pub dest="{{ inventory_dir }}/files/sync-user@{{ inventory_hostname }}.pub" flat=yes
...
