---
- hosts: all
  connection: local
  gather_facts: false
  tags: always
  tasks:
    # NB: don't forget to update ../.travis.yml
    - name: ensure team@ has same ansible_version # kill incompatibility ASAP
      assert:
        msg: "ansible_version: {{ ansible_version }}"
        that:
          - ansible_version.major == 2
          - ansible_version.minor == 4
          - ansible_version.revision == 2
          - playbook_dir == inventory_dir
      run_once: true

    - name: "notify #ooni-bots at openobservatory.slack.com"
      slack:
        token: "{{ ansible_slack_token }}"
        channel: "#ooni-bots"
        msg: "{{ lookup('template', 'ansible-playbook-slack.j2') }}"
      delegate_to: localhost
      run_once: true
      when: lookup('env', 'TRAVIS_VAULT_SECRET' ) | length == 0
...
