---
- import_playbook: ansible-version.yml

- hosts: jupyter.ooni.io
  gather_facts: true
  vars:
    letsencrypt_nginx: yes
    letsencrypt_domains: "jupyter.ooni.io"
  roles:
    - letsencrypt
    - jupyter
