---
- include: ansible-version.yml

- hosts: hkgmetadb.infra.ooni.io
  gather_facts: false # no useful facts there :)
  roles:
    - role: pguser-readonly
      login_user: shovel # FIXME: revoke superuser access from this user :)
      login_password: '{{ shovel_postgres_password }}'
      db: metadb
      name: oosuperset
      password: '{{ hkgsuperset_postgres_password }}'

- hosts: hkgsuperset.ooni.io
  become: false
  remote_user: root
  gather_facts: true
  pre_tasks:
    - name: bootstap python
      raw: if [ ! -x /usr/bin/python ]; then apt-get update && apt-get -y install python-simplejson python-apt; fi
      register: output
      changed_when: output.stdout != ""
  roles:
    - role: adm
      adm_passwd:
        - "{{ passwd.art }}"
        - "{{ passwd.darkk }}"

- hosts: hkgsuperset.ooni.io
  gather_facts: false # already gathered
  vars:
    letsencrypt_nginx: yes
    letsencrypt_domains: "hkgsuperset.ooni.io"
  roles:
    - letsencrypt
    - superset
