---
- import_playbook: ansible-version.yml

- hosts: db-1.proteus.test.ooni.io
  vars:
    psql_db_name: proteus
    psql_db_user: proteus
    psql_db_passwd: "{{ orchestra_database_password_testing }}"
  roles:
    - role: postgresql
      tags: postgresql

- hosts: db-1.proteus.ooni.io
  vars:
    psql_db_name: "{{ orchestra_database_username }}"
    psql_db_user: "{{ orchestra_database_name }}"
    psql_db_passwd: "{{ orchestra_database_password }}"
  roles:
    - role: postgresql
      tags: postgresql

- import_playbook: deploy-ooni-registry.yml

- import_playbook: deploy-ooni-orchestrate.yml

- import_playbook: deploy-orchestra-notify.yml

- import_playbook: deploy-orchestra-frontend.yml
