---
- import_playbook: ansible-version.yml

- hosts: mia-ps-test.ooni.nu
  tags: test
  roles:
    - role: docker
      tags: base
    - role: letsencrypt
      tags: tls
      expand: yes
      with_nginx: yes
      letsencrypt_domains:
        - "mia-ps-test.ooni.nu"
        - "ps-test.ooni.io"
    - role: ooni-bouncer
      tags:
        - service
        - bouncer
    - role: ooni-collector
      with_nginx: no
      tags:
        - service
        - collector
    - role: probe-services
      tags: ps

- hosts: mia-ps2.ooni.nu
  roles:
    - role: docker
    - role: letsencrypt
      expand: yes
      tags: tls
      letsencrypt_domains:
        - "mia-ps2.ooni.nu"
        - "ps2.ooni.io"
    - role: ooni-bouncer
      tags:
        - service
        - bouncer
    - role: ooni-collector
      tags:
        - service
        - collector
    - role: probe-services
      tags: ps
    - role: onion-service
      tags: tor
      onion_services:
      - "{{ collector_service_v2 }}"

- hosts: ams-ps2.ooni.nu
  roles:
    - role: docker
    - role: letsencrypt
      expand: yes
      tags: tls
      letsencrypt_domains:
        - "ams-ps2.ooni.nu"
        - "ps1.ooni.io"
        - "collector.ooni.io"
        - "a.collector.ooni.io"
        - "b.collector.ooni.io"
        - "c.collector.ooni.io"
    - role: ooni-bouncer
      tags:
        - service
        - bouncer
    - role: ooni-collector
      tags:
        - service
        - collector
    - role: probe-services
      tags: ps
    - role: onion-service
      tags: tor
      onion_services:
      - "{{ collector_service_v2 }}"

- hosts: ams-ps.ooni.nu
  roles:
    - role: docker
    - role: letsencrypt
      expand: yes
      tags: tls
      letsencrypt_domains:
        - "ams-ps.ooni.nu"
        - "ps.ooni.io"
        - "ps4.ooni.io"
        - "bouncer.ooni.io"
        - "registry.ooni.io"
        - "orchestrate.ooni.io"
        # Legacy addresses
        - "events.proteus.ooni.io"
        - "registry.proteus.ooni.io"
    - role: ooni-bouncer
      tags:
        - service
        - bouncer
    - role: ooni-collector
      tags:
        - service
        - collector
    - role: probe-services
      tags: ps
    - role: onion-service
      tags: tor
      onion_services:
      - "{{ bouncer_service_v2 }}"
      - "{{ collector_service_v2 }}"

- hosts: hkg-ps.ooni.nu
  roles:
    - role: docker
      tags: base
    - role: letsencrypt
      tags: base
      expand: yes
      letsencrypt_domains:
        - "hkg-ps.ooni.nu"
        - "ps3.ooni.io"
    - role: ooni-bouncer
      tags:
        - service
        - bouncer
    - role: ooni-collector
      tags:
        - service
        - collector
    - role: probe-services
      tags: ps
