---
- import_playbook: ansible-version.yml

- hosts: prometheus.infra.ooni.io
  roles:
    - docker_py
    - role: mon.ooni.nu
      tags: mon.ooni.nu
    - role: letsencrypt
      letsencrypt_domains: ['mon.ooni.nu']
      tags: mon.ooni.nu
    # prometheus roles do not need extra `pip` modules and `local_action` should use default python
    - role: alertmanager
      tags: alertmanager
    - role: ooca-cert
      ooca_ssl_dir: '{{ prometheus_ssl_dir }}'
      ooca_ssl_subj: '/O=OONI/OU=Prometheus Scraper/CN={{ inventory_hostname }}'
      ooca_ca: scraper_ca
      ooca_group: prometh
    - role: prometheus
      tags: prometheus
    - role: blackbox_exporter
      tags: blackbox_exporter
    - role: pushgateway
      tags: pushgateway
    - role: letsencrypt
      letsencrypt_domains: ['prometheus.infra.ooni.io'] # legacy hostname-based pushgateway domain
      tags: pushgateway

- hosts: prometheus.infra.ooni.io
  gather_facts: false # already gathered
  vars:
    ansible_python_interpreter: "/root/venv/bin/python2.7"
  roles:
    - role: grafana
      tags: grafana
