---
- import_playbook: ansible-version.yml

- hosts: hkgbouncer.ooni.nu
  roles:
    - role: docker_py
    - role: letsencrypt
      letsencrypt_nginx: true
      letsencrypt_domains: bouncer.ooni.io

- hosts: hkgbouncer.ooni.nu
  gather_facts: false # no useful facts there :)
  vars:
    ansible_python_interpreter: '/root/venv/bin/python2.7'
  roles:
    - role: ooni-bouncer
      tags: ooni-bouncer
      bouncer_domain: bouncer.ooni.io
