---
- hosts: proteus.test.ooni.io
  vars:
    orchestra_frontend_https_port: 443
    orchestra_orchestrate_url: "https://events.proteus.test.ooni.io"
    orchestra_registry_url: "https://registry.proteus.test.ooni.io"
    letsencrypt_nginx: yes
    letsencrypt_domains: "{{ inventory_hostname }}"
  roles:
    - letsencrypt
    - nodejs
    - orchestra-frontend

- hosts: proteus.ooni.io
  vars:
    orchestra_frontend_https_port: 443
    orchestra_orchestrate_url: "https://events.proteus.ooni.io"
    orchestra_registry_url: "https://registry.proteus.ooni.io"
    letsencrypt_nginx: yes
    letsencrypt_domains: "{{ inventory_hostname }}"
  roles:
    - letsencrypt
    - nodejs
    - orchestra-frontend
