# This playbook updates data at ooni-sysadmin.git/ext/
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: get git-root
      command: git rev-parse --show-toplevel
      register: extroot
      changed_when: false

    - set_fact:
        extroot: '{{ extroot.stdout }}/ext'
        socks5: '{{ 32767 | random(1024) }}'
        jumphost: '{{ namecheap_jumphosts | random }}'
    - name: ssh jumphost ({{ jumphost }})
      command: ssh -D {{ socks5 }} -o BatchMode=yes -N {{ jumphost }}
      async: 60
      poll: 0
    - wait_for: port={{ socks5 }} timeout=10

    - set_fact: namecheap_api=https://api.namecheap.com/xml.response?ApiUser={{ namecheap_user }}&ApiKey={{ namecheap_token }}&UserName={{ namecheap_user }}&ClientIp={{ lookup('dig', jumphost, 'qtype=A') }}

    # curl is used instead of M(uri) to pass traffic through socks5 jumphost so cleartext
    # namecheap_token does not touch disk of jumphost as a temporary file created by ansible
    - name: fetch zone
      command: curl -sS --socks5-hostname localhost:{{ socks5 }} "{{ namecheap_api }}&Command=namecheap.domains.dns.getHosts&{{ item }}"
      register: zones # becomes a _list_ of results after the task
      changed_when: false
      failed_when: "'    </DomainDNSGetHostsResult>' not in zones.stdout_lines"
      with_items:
        - SLD=ooni&TLD=io
        - SLD=ooni&TLD=nu
        - SLD=openobservatory&TLD=org

    - name: fetch gh droplets
      uri:
        url: https://portal.eclips.is/portal/api/v2/droplets
        headers: { Authorization: 'Bearer {{ gh_token }}' }
        return_content: yes
      register: droplets

    - copy:
        content: "{{ item.0.stdout | regex_replace('<Server>[^<]+</Server>', '<Server/>') | regex_replace('<ExecutionTime>[^<]+</ExecutionTime>', '<ExecutionTime/>') }}"
        dest: '{{ extroot }}/{{ item.1 }}.xml'
      with_together:
        - '{{ zones.results }}'
        - [ ooni.io, ooni.nu, openobservatory.org ]
      loop_control:
        label: '{{ item.1 }}'
    - name: save gh-droplets.json
      copy:
        content: '{{ droplets.json | to_nice_json }}'
        dest: '{{ extroot }}/gh-droplets.json'

    - set_fact:
        files: '{{extroot}}/ooni.io.xml {{extroot}}/ooni.nu.xml {{extroot}}/openobservatory.org.xml {{extroot}}/gh-droplets.json'
    - name: git add
      command: git add {{ files }}
      changed_when: false
    - name: git diff
      command: git diff HEAD -- {{ files }}
      changed_when: false
      register: diff
    - name: git commit
      command: git commit -m 'Current external inventory state' -- {{ files }}
      when: diff.stdout | length > 0
