---
- name: Stage instance(s)
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    keypair: ooni-pipeline
    instance_type: m3.medium
    security_group: ooni-pipeline-computer-1
    image: ami-1ecae776
    region: us-east-1
  tasks:
    - name: Launch instance {{ instance_type }}
      ec2: 
        keypair: "{{ keypair }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        count: 1
        region: "{{ region }}"
      register: ec2

    - name: Add new instances to host group
      add_host: hostname={{item.public_ip}} groupname=computer
      with_items: ec2.instances

    - name: Wait for the instances to boot by checking the ssh port
      wait_for: host="{{item.public_dns_name}}" port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

#   Use the ec2_vol module to create volumes for attachment to each instance.
#   Use with_items to attach to each instance (by returned id) launched previously.

# 
#   - name: Create a volume and attach
#     ec2_vol: volume_size=20 instance={{item.id}}
#     with_items: ec2.instances
# 

- name: Configure instance
  hosts: computer
  user: ec2-user
  vars:
    virtualenv_name: trackmap
    user: ec2-user
    papertrail_hostname: "logs2.papertrailapp.com"
    papertrail_port: "57492"
    playbook: "trackmap"
  tasks:
    - include: roles/trackmap/tasks/install_trackmap.yml
      when: playbook == "trackmap"
    - include: roles/trackmap/tasks/run.yml
      when: playbook == "trackmap"


- name: Terminate instances
  hosts: localhost
  connection: local
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'
