# This task is to copy the script to copy the script for running a metadb snapshot update into /srv/
# You shall then ssh into hkgmetadb.infra.ooni.io and trigger the script via sh
# /srv/metadb-snapshot.sh inside of a screen/tmux session
- hosts: hkgmetadb.infra.ooni.io
  tasks:
    - name: write /srv/metadb-snapshot.sh
      template:
        src: metadb-snapshot.sh
        dest: /srv/metadb-snapshot.sh
