- name: download gorush exe
  get_url:
    url: "{{ gorush_url }}"
    dest: "{{ orchestra_install_path }}"
    mode: 0755

- name: Configure gorush
  notify:
  - restart gorush
  template:
    src: gorush.yml.j2
    dest: "{{ orchestra_config_path }}/gorush.yml"

- name: Write Proteus APN key
  notify:
  - restart gorush
  copy:
    content: "{{ orchestra_apn_key_content }}"
    dest: "{{ orchestra_config_path }}/apn-key.pem"

- name: Install gorush systemd service file
  notify:
  - restart gorush
  template:
    src: gorush.service
    dest: /etc/systemd/system/gorush.service

- name: Enable and start gorush service
  systemd:
    name: gorush.service
    state: started
    enabled: yes
    daemon_reload: yes
