---
- name: Install nginx
  environment:
    RUNLEVEL: 1
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "nginx"
    - "python-passlib"

- name: Remove default nginx virtual host
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Create password file for nginx
  htpasswd:
    path: /etc/nginx/orchestra.htpasswd
    name: "{{ orchestra_notify_basic_auth_user }}"
    password: "{{ orchestra_notify_basic_auth_password }}"
    owner: root
    group: www-data
    mode: 0640

- name: Create password file for prometheus endpoint
  copy:
    dest: /etc/nginx/orchestra-notify-prometheus.htpasswd
    owner: root
    group: www-data
    mode: 0640
    content: "prometheus_scraper:{SSHA}{{ prometheus_scraper_ssha }}\n"

- name: Add nginx virtual host config
  template:
    src: orchestra_nginx.conf.j2
    dest: /etc/nginx/sites-enabled/orchestra
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
...
