---
- template: src=ngx-oomsm-web dest=/etc/nginx/sites-enabled/oomsm-web
  notify: reload nginx

- name: docker network for measurements
  docker_network:
    name: msm
    driver_options:
      com.docker.network.bridge.name: brmsm
    ipam_options:
      subnet: 172.25.232.0/24
      gateway: 172.25.232.1

- name: ooni-measurements webservice
  docker_container:
    image: openobservatory/ooni-api:{{ oomsm_tag }}
    name: oomsm-web
    hostname: oomsm-web
    networks: [{name: msm, ipv4_address: '{{ oomsm_backend_ipv4 }}'}]
    purge_networks: true
    env:
      APP_ENV: production
      DATABASE_URL: 'postgresql://oomsm-beta:{{ oomsm_beta_postgres_password }}@hkgmetadb.infra.ooni.io/metadb' # FIXME: ?sslmode=require
      AUTOCLAVED_BASE_URL: 'http://datacollector.infra.ooni.io/ooni-public/autoclaved/' # FIXME: use dataproxy when API moves to AMS
    command: gunicorn --bind 0.0.0.0:{{ oomsm_backend_port }} --workers 5 --timeout {{ oomsm_request_timeout }} measurements.wsgi
    user: "{{ passwd.oomsmweb.id }}:{{ passwd.oomsmweb.id }}"
    restart_policy: unless-stopped
