---
- name: api.ooni.io nginx config
  template: src=ngx-oomsm-web dest=/etc/nginx/sites-enabled/oomsm-web
  notify: reload nginx
  tags: legacy

- name: docker network for measurements
  docker_network:
    name: msm
    driver_options:
      com.docker.network.bridge.name: brmsm
    ipam_options:
      subnet: 172.25.232.0/24
      gateway: 172.25.232.1

- name: ooni-api webservice
  docker_container:
    image: openobservatory/api:{{ oomsm_tag }}
    name: oomsm-web
    hostname: oomsm-web
    networks: [{name: msm, ipv4_address: '{{ oomsm_backend_ipv4 }}'}]
    purge_networks: true
    env:
      APP_ENV: production
      DATABASE_URL: '{{ oomsm_db_url }}' # FIXME: ?sslmode=require
      DATABASE_STATEMENT_TIMEOUT: '{{ (oomsm_timeout_s - 1) * 1000 }}'
      AUTOCLAVED_BASE_URL: 'http://s3.amazonaws.com/ooni-data/autoclaved/jsonl.tar.lz4/' # HOTFIX 'http://datacollector.infra.ooni.io/ooni-public/autoclaved/' # FIXME: use dataproxy when API moves to AMS
      CENTRIFUGATION_BASE_URL: 'http://datacollector.infra.ooni.io/ooni-public/centrifugation/'
    command: gunicorn --bind 0.0.0.0:{{ oomsm_backend_port }} --workers 5 --timeout 60 measurements.wsgi
    user: "{{ passwd.oomsmweb.id }}:{{ passwd.oomsmweb.id }}"
    restart_policy: unless-stopped
