---

- name: Create {{ slack_irc_dir }} dir
  tags: slack-irc
  file:
    path: "{{ slack_irc_dir }}"
    state: directory

- name: Create slack-irc-bridge config
  tags: slack-irc
  copy:
    content: "{{ slack_irc_config }}"
    dest: "{{ slack_irc_dir }}/config.json"
  notify: restart slack-irc-bridge

- name: Deploy slackin, letsecnrypt containers
  tags: slackin
  docker_service:
    project_name: slackin
    definition:
      version: '2'
      services:
        https-portal:
          image: steveltn/https-portal:1.2.4
          restart: always
          environment:
            DOMAINS: "{{ slackin_domains }}"
            PRODUCTION: "TRUE"
          ports:
            - "80:80"
            - "443:443"
          links:
            - slackin
        slackin:
          image: chk1/slackin
          restart: always
          ports:
            - "3000:3000"
          environment:
            SLACKIN_VERSION: latest
            SLACK_ORG: "{{ slackin_org }}"
            SLACK_TOKEN: "{{ slackin_token }}"

- name: Deploy slack-irc-bridge container
  tags: slack-irc
  docker_container:
    name: slack-irc-bridge
    image: chihchun/slack-ircbridge
    restart_policy: always
    volumes:
      - "{{ slack_irc_dir }}:/slack-irc"
