oonibackend_package: oonibackend
enable_dns_helper: yes
enable_dns_discovery_helper: yes
enable_http_return_json_headers_helper: yes
enable_tcp_echo_helper: yes
enable_ssl_helper: no
enable_daphn3_helper: yes
enable_tls_bouncer: no
enable_tls_collector: no
enable_tls_web_connectivity: no
enable_web_connectivity: yes

dns_resolver_address: "8.8.8.8:53"
dns_test_helper_address: "213.138.109.232:57004"
http-return-json-headers_address: "http://93.95.227.200"
ssl_address:
tcp_echo_address: "213.138.109.232"
traceroute_address: "213.138.109.232"
web_connectivity_domain: "{{ letsencrypt_domain_list|selectattr("role", "equalto", "collector")|map(attribute='domain')|list }}"
web_connectivity_hs: "{{ web_connectivity_hsdir_hostname.stdout }}"
collector_hs: "{{ collector_hsdir_hostname.stdout }}"
mlab_ns_query_url_ansible: "{{ http://mlab-ns.appspot.com/ooni?policy=all }}"
dst_bouncer_path_ansible: "{{/data/bouncer/bouncer.yaml}}"
base_bouncer_path_ansible: "{{/data/bouncer/bouncer-base.yaml}}"

http_return_json_headers_port: 57001
tcp_echo_port: 57002
daphn3_port: 57003
dns_port_tcp: 57004
dns_port_udp: 57004
dns_discover_port_tcp: 57005
dns_discover_port_udp: 57005
ssl_port: 57006
tls_bouncer_port: 10443
tls_collector_port: 11443

enable_bouncer: no
enable_policy: no
archive_dir: "{{ oonibackend_data_path }}/archive"
tor_datadir: "{{ oonibackend_data_path }}/tor"
bouncer_file: "{{ oonibackend_data_path }}/bouncer-base.yaml"
policy_file: "{{ oonibackend_data_path }}/policy.yaml"
deck_dir: "{{ oonibackend_data_path }}/decks"
input_dir: "{{ oonibackend_data_path }}/inputs"
report_dir: "{{ oonibackend_data_path }}/raw_reports"
bouncer_hsdir: "{{ tor_datadir }}/bouncer"
collector_hsdir: "{{ tor_datadir }}/collector"
web_connectivity_hsdir: "{{ tor_datadir }}/web_connectivity"
bouncer_update_file: "{{ oonibackend_data_path }}/update-bouncer.py"
web_connencivity_crt_bundle: "{{ oonibackend_certbundle }}"
bouncer_crt_bundle: "{{ oonibackend_certbundle }}"
tls_collector_crt_bundle: "{{ oonibackend_certbundle }}"

oonibackend_install_path: /opt/ooni-backend
oonibackend_log_path: /var/log/ooni
oonibackend_conf: /etc/oonibackend.conf
oonibackend_log_file_name: oonibackend.log
