---
- name: restart af-sched
  docker_container: name=af-sched restart=true
  listen: restart airflow

- name: restart af-websrv
  docker_container: name=af-websrv restart=true
  listen: restart airflow

- name: restart af-worker
  docker_container: name=af-worker restart=true
  listen: restart airflow
